### ISSUE TITLE
Can't import to Web Extension Translator

### ISSUE THREAD

**Issue by NightSharp** [piroor/tst-tab-drag-handle#1]
In https://lusito.github.io/web-ext-translator/
I want to load this project buf failed. This make me hard to translate the addon to my language.
I don't know how to generate hash in each item and so so.

**Comment by piroor** [comment]
How did you tried? I've tried with the URL `https://github.com/piroor/tst-tab-drag-handle` (not `https://github.com/piroor/tst-tab-drag-handle.git`) and successfully loaded:
![image](https://user-images.githubusercontent.com/70062/77229603-3e416a00-6bd2-11ea-92ba-fd9118bd299d.png)

**Comment by NightSharp** [comment]
> 
> 
> How did you tried? I've tried with the URL `https://github.com/piroor/tst-tab-drag-handle` (not `https://github.com/piroor/tst-tab-drag-handle.git`) and successfully loaded:
> ![image](https://user-images.githubusercontent.com/70062/77229603-3e416a00-6bd2-11ea-92ba-fd9118bd299d.png)

Thanks, It may be my network problem...
I have completed this translation.
