### ISSUE TITLE
Delays not working

### ISSUE THREAD

**Issue by harl** [piroor/tst-tab-drag-handle#9]
The two delays (in milliseconds), that are supposed to be applied when the drag handles are shown or hidden respectively, aren't working for me at all.  The drag handles are always shown / hidden instantly.

TST Tab Drag Handle 1.0.1

**Comment by piroor** [comment]
Those delays are used as values for `transition` and `animation` CSS properties . If they are disabled by some reasons (Firefox's features or platform settings) or overridden by any user style rules, animation effects may not be applied as expected. Do you use any of these possible factors?

**Comment by harl** [comment]
You're correct. I usually always keep those built-in "performance options" disabled in Windows. I had no idea those were having an effect on CSS properties (and notifications too).
The one called "Animate controls and elements inside windows" is directly causing the drag handles' delays not to work.
After enabling that option, the delays immediately work again, but of course I also get a bunch of less useful "animations" across windows programmes.

Thanks for helping me with this. :)
